from .aggregates import CORPUS_FACETS, COUNT_RECORDS
from .passages import SEARCH_PASSAGES
from .records import FIND_RECORDS
from .sections import READ_RECORD_SECTIONS

TOOLS = (SEARCH_PASSAGES, FIND_RECORDS, READ_RECORD_SECTIONS, COUNT_RECORDS, CORPUS_FACETS)
