# Generated by Django 5.1.15 on 2026-09-03 19:09
#
# This migration only creates a new table and seeds one row into it — it
# does not touch RecordEmbedding's schema or data in any way. That is
# deliberate: ADR-015 calls the pre-existing hardcoded vector dimension a
# one-way door, so the safe order is "add the source of truth first,
# migrate what reads it later" rather than altering a live vector column in
# the same change that introduces the thing meant to govern it. A database
# that already holds RecordEmbedding rows is unaffected by this migration
# beyond gaining this new, independent table.

from django.conf import settings
from django.db import migrations, models


def seed_active_embedding_space(apps, schema_editor):
    """Seed exactly one active space from current settings.

    Reads live settings rather than a value frozen into the migration,
    because this is a one-time bootstrap of "whatever this deployment is
    already configured to embed with" — not a schema change, so there is
    nothing here for a future settings change to silently invalidate.
    Guarded by ``get_or_create`` so replaying this migration (e.g. in a
    fresh test database) never creates a second active row and trips the
    partial unique constraint above it.
    """
    EmbeddingSpace = apps.get_model("ai", "EmbeddingSpace")
    EmbeddingSpace.objects.get_or_create(
        state="active",
        defaults={
            "model_id": settings.AI_EMBEDDING_MODEL,
            "dimensions": settings.AI_EMBEDDING_DIMENSIONS,
            "metric": "cosine",
        },
    )


def unseed_active_embedding_space(apps, schema_editor):
    EmbeddingSpace = apps.get_model("ai", "EmbeddingSpace")
    EmbeddingSpace.objects.filter(state="active").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_embeddingjob_recordembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=200)),
                ('dimensions', models.PositiveIntegerField()),
                ('metric', models.CharField(default='cosine', max_length=20)),
                ('state', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('state',), name='one_active_embedding_space')],
            },
        ),
        migrations.RunPython(
            seed_active_embedding_space,
            reverse_code=unseed_active_embedding_space,
        ),
    ]
