# Generated by Django 5.1.15 on 2026-09-03 19:09
#
# This migration only creates a new table and seeds one row into it — it
# does not touch RecordEmbedding's schema or data in any way. That is
# deliberate: ADR-015 calls the pre-existing hardcoded vector dimension a
# one-way door, so the safe order is "add the source of truth first,
# migrate what reads it later" rather than altering a live vector column in
# the same change that introduces the thing meant to govern it. A database
# that already holds RecordEmbedding rows is unaffected by this migration
# beyond gaining this new, independent table.

from django.db import migrations, models

#: What this migration seeded when it was written: the OpenAI model the code
#: then assumed, at the dimension migration 0002 hardcoded. Frozen as literals
#: by IR-280, which deleted the `AI_EMBEDDING_*` settings this used to read.
#: A migration is a record of what happened, so it must keep describing that
#: even once the settings it read are gone; migration 0007 supersedes this row
#: with the `voyage-context-4` space ADR-015 decided on.
_SEEDED_MODEL_ID = "text-embedding-3-small"
_SEEDED_DIMENSIONS = 1536


def seed_active_embedding_space(apps, schema_editor):
    """Seed exactly one active space: the one this deployment was embedding
    with when this migration was written.

    Guarded by ``get_or_create`` so replaying this migration (e.g. in a
    fresh test database) never creates a second active row and trips the
    partial unique constraint above it.
    """
    EmbeddingSpace = apps.get_model("ai", "EmbeddingSpace")
    EmbeddingSpace.objects.get_or_create(
        state="active",
        defaults={
            "model_id": _SEEDED_MODEL_ID,
            "dimensions": _SEEDED_DIMENSIONS,
            "metric": "cosine",
        },
    )


def unseed_active_embedding_space(apps, schema_editor):
    EmbeddingSpace = apps.get_model("ai", "EmbeddingSpace")
    EmbeddingSpace.objects.filter(state="active").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_embeddingjob_recordembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=200)),
                ('dimensions', models.PositiveIntegerField()),
                ('metric', models.CharField(default='cosine', max_length=20)),
                ('state', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('state',), name='one_active_embedding_space')],
            },
        ),
        migrations.RunPython(
            seed_active_embedding_space,
            reverse_code=unseed_active_embedding_space,
        ),
    ]
