# Generated by Django 5.1.15 on 2026-09-03 19:52, hand-edited (IR-89 F).
#
# The autodetector's output named the new chunk model "DocumentChunkNew" —
# a rename dance used to get it to treat the field-less DocumentChunk stub
# from migration 0001 as replaced outright rather than prompt interactively
# for defaults on new non-nullable columns (including a foreign key) it has
# no sensible way to guess for a table it can't know is empty. That stub was
# never written to by any code path (verified against the tree), so
# deleting and recreating it is safe. Renamed back to DocumentChunk here,
# with the DeleteModel moved first: Django's migration state is a name-keyed
# map applied operation by operation, so a rename-in-place without also
# reordering would have this state machine read as "create DocumentChunk,
# then immediately delete the model just created" instead of "delete the
# old placeholder, then create the real thing" — deleting first is what
# makes the two same-named models resolve to the old and the new,
# respectively, at each point in this migration.

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_embedding_space'),
        ('records', '0008_add_completed_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_embeddings', to='ai.embeddingspace')),
            ],
        ),
        migrations.CreateModel(
            name='ChunkSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_hash', models.CharField(max_length=64)),
                ('strategy_id', models.CharField(max_length=100)),
                ('options', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_sets', to='records.record')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('max_sequence', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('content', models.TextField()),
                ('context_path', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('token_count', models.PositiveIntegerField()),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('element_kinds', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('bboxes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.chunkset')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='records.record')),
            ],
        ),
        migrations.AddField(
            model_name='chunkembedding',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='ai.documentchunk'),
        ),
        migrations.AddConstraint(
            model_name='chunkset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('record',), name='one_active_chunk_set_per_record'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['record', 'sequence'], name='ai_chunk_record_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('chunk_set', 'sequence'), name='unique_sequence_per_chunk_set'),
        ),
        migrations.AddIndex(
            model_name='chunkembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='chunkembedding',
            constraint=models.UniqueConstraint(fields=('chunk', 'space'), name='unique_chunk_embedding_per_space'),
        ),
    ]
