# Generated by Django 5.1.15 on 2026-09-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_chunk_persistence'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkset',
            name='page_sizes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
