# Generated by Django 5.1.15 on 2026-09-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_chunkset_page_sizes'),
        ('records', '0008_add_completed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_hash', models.CharField(max_length=64)),
                ('strategy_id', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracted', 'Extracted'), ('chunked', 'Chunked'), ('indexed', 'Indexed'), ('stale', 'Stale'), ('failed', 'Failed')], db_index=True, default='extracted', max_length=20)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='records.record')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='ai.embeddingspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('record', 'extraction_hash', 'strategy_id', 'space'), name='unique_ingestion_job_identity')],
            },
        ),
    ]
