# Generated by Django 5.1.15 on 2026-09-21 15:29
#
# TurnEmbedding (IR-297): mirrors ChunkEmbedding, keyed by (turn, space).

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_turn_resolved_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_embeddings', to='ai.embeddingspace')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='ai.turn')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='turn_embedding_hnsw_idx', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('turn', 'space'), name='unique_turn_embedding_per_space')],
            },
        ),
    ]
