# Generated by Django 5.1.15 on 2026-09-23 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_alter_turn_state'),
        ('records', '0012_pipeline_status_in_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('degraded', models.BooleanField(default=False)),
                ('model_id', models.CharField(blank=True, max_length=200)),
                ('content_hash', models.CharField(max_length=64)),
                ('prompt_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_overview', to='records.record')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentSummary',
        ),
    ]
