# Generated by Django 5.1.15 on 2026-10-06 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0017_turn_answer_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowEvidenceTally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShadowEvidenceDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('outcome', models.CharField(blank=True, max_length=40)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claims', models.PositiveSmallIntegerField(default=0)),
                ('reclaims', models.PositiveSmallIntegerField(default=0)),
                ('fenced_out_completions', models.PositiveSmallIntegerField(default=0)),
                ('manifest', models.JSONField()),
                ('detector', models.JSONField()),
                ('decision', models.JSONField(blank=True, null=True)),
                ('route', models.CharField(blank=True, max_length=12)),
                ('parity_matched', models.BooleanField(null=True)),
                ('parity_differences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_shadow', to='ai.turn')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'claimed_at'], name='ai_shadowev_status_e73e7d_idx')],
            },
        ),
    ]
