# Generated by Django 5.1.15 on 2026-05-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ACCESS', 'Record Access'), ('UPLOAD', 'File Upload'), ('DOWNLOAD', 'File Download'), ('DELETE', 'File Delete'), ('RENAME', 'File Rename'), ('UNAUTHORIZED_BYPASS', 'Unauthorized Access Attempt')], db_index=True, max_length=30),
        ),
    ]
