# Generated by Django 5.1.15 on 2026-09-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('ACCESS', 'Record Access'), ('UPLOAD', 'File Upload'), ('DOWNLOAD', 'File Download'), ('DELETE', 'File Delete'), ('RENAME', 'File Rename'), ('PIN_GENERATED', 'PIN Generated'), ('PIN_VERIFIED', 'PIN Verified'), ('ROLE_CHANGE', 'Role Change'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('SESSION_REVOKE', 'Session Revoked')], db_index=True, max_length=20),
        ),
    ]
