# Generated by Django 5.1.15 on 2026-05-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_roles_colleges_departments_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
