# Generated by Django 5.1.15 on 2026-10-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_unset_is_staff_on_office_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_office_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
