# Generated by Django 5.1.15 on 2026-05-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_pipeline_parallel_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pipeline_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('adviser_review', 'Adviser Review'), ('rdco_intake', 'RDCO Intake Review'), ('itso_review', 'ITSO Review'), ('parallel_review', 'Parallel Office Review'), ('rdco_review', 'RDCO Final Review'), ('published', 'Published'), ('declined', 'Declined'), ('rejected', 'Rejected'), ('pending_delete', 'Pending Deletion')], db_index=True, default='draft', max_length=20),
        ),
    ]
