# Generated by Django 5.1.15 on 2026-09-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_add_completed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='requested_ierc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='requested_itso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='requested_ktto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='requires_ethics_review',
            field=models.BooleanField(default=False),
        ),
    ]
