# Generated by Django 5.1.15 on 2026-09-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_add_office_routing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='last_resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='resubmission_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
