# Generated by Django 5.1.15 on 2026-09-10 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_record_last_resubmitted_at_record_resubmission_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dpa_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When DPA consent was accepted for this disclosure. Null means never.', null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='dpa_accepted_by',
            field=models.ForeignKey(blank=True, help_text='Who accepted. SET_NULL so a deleted account cannot erase the timestamp.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpa_accepted_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
