# Generated by Django 5.1.15 on 2026-09-29 23:40

import apps.records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_pipeline_status_in_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='abstract_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.records.models.abstract_file_path),
        ),
    ]
