# Generated by Django 5.1.15 on 2026-10-08 03:16

import apps.records.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_record_abstract_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('manuscript', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.records.models.abstract_file_path)),
                ('cause', models.CharField(choices=[('submission', 'Submission'), ('revision', 'Revision')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_versions', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='records.record')),
            ],
            options={
                'ordering': ['record', 'number'],
                'constraints': [models.UniqueConstraint(fields=('record', 'number'), name='record_version_number_unique')],
            },
        ),
    ]
