# Generated by Django 5.1.15 on 2026-09-04, renamed by hand (IR-107).
#
# Additive only: three nullable-by-default columns on an existing table, so
# it applies to a populated database without a rewrite and without a default
# anyone has to justify.
#
# What existing rows mean afterwards is worth stating, because it is not
# "unextracted". A `done` row from before this migration has `extracted_text`
# and an empty `structure` — it was produced by the prototype chain, which
# had no structure to give. `PdfExtraction.as_normalized_document()` returns
# None for exactly those rows rather than an empty document, so a chunking
# run skips them instead of writing an empty chunk set over a real thesis.
# Re-extracting them is a backfill (IR-116), not a migration.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_seed_upload_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfextraction',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pdfextraction',
            name='extractor',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='pdfextraction',
            name='structure',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
