# Generated by Django 5.1.15 on 2026-09-07 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_upload_slots_are_not_required'),
        ('records', '0010_record_last_resubmitted_at_record_resubmission_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfextraction',
            name='record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_extraction', to='records.record'),
        ),
        migrations.AlterField(
            model_name='pdfextraction',
            name='upload',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_extraction', to='documents.recordupload'),
        ),
        migrations.AddConstraint(
            model_name='pdfextraction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('record__isnull', True), ('upload__isnull', False)), models.Q(('record__isnull', False), ('upload__isnull', True)), _connector='OR'), name='pdfextraction_exactly_one_of_upload_or_record'),
        ),
    ]
