# Generated by Django 5.1.15 on 2026-09-14 06:09

from django.db import migrations, models


def set_kind_from_owner(apps, schema_editor):
    """Backfill IR-239's `kind` for rows written before it existed.

    Which FK is set is exactly the endpoint coincidence IR-239 removes as the
    *decision* rule -- but for rows already in the table it is the only
    evidence of what they hold, and for those rows it is reliable: until this
    migration there was no path that attached a manuscript to an UploadSlot.
    Reading it once, here, is what lets every later read go through `kind`.
    """
    PdfExtraction = apps.get_model("documents", "PdfExtraction")
    PdfExtraction.objects.filter(record__isnull=False).update(kind="manuscript")
    PdfExtraction.objects.filter(upload__isnull=False).update(kind="supplementary")


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_pdfextraction_manuscript_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfextraction',
            name='kind',
            field=models.CharField(choices=[('manuscript', 'Manuscript'), ('supplementary', 'Supplementary')], db_index=True, default='supplementary', max_length=16),
        ),
        migrations.RunPython(set_kind_from_owner, migrations.RunPython.noop),
    ]
