# Generated by Django 5.1.15 on 2026-09-23 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_pdfextraction_kind'),
        ('records', '0012_pipeline_status_in_review'),
        # 0007, not 0008: RecordAssignment is all this needs, and depending on
        # the backfill would make rewinding it (test_shadow_backfill_migration)
        # unapply this migration too.
        ('reviews', '0007_reviewer_directed_routing_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadslot',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_slots', to='records.record'),
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(choices=[('adviser', 'Adviser'), ('intake', 'Intake & Triage'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], max_length=20)),
                ('message', models.TextField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('withdrawn', 'Withdrawn')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests', to='reviews.recordassignment')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='records.record')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['record', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('missing', 'Missing'), ('uploaded', 'Uploaded'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='missing', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.documentrequest')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_items', to='documents.uploadslot')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_items', to='documents.recordupload')),
            ],
            options={
                'ordering': ['request', 'sort_order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['record', 'state'], name='documents_d_record__9b5145_idx'),
        ),
    ]
