# Generated by Django 5.1.15 on 2026-09-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='withdrawal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentrequestitem',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequestitem',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
