# Generated by Django 5.1.15 on 2026-10-09 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_recordfile_party'),
        ('reviews', '0012_recordassignment_closed_by_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='closed_by_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='closed_document_requests', to='reviews.review'),
        ),
    ]
