# Generated by Django 5.1.15 on 2026-10-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documentrequest_closed_by_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='party',
            field=models.CharField(choices=[('adviser', 'Adviser'), ('intake', 'Intake (retired)'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recordfile',
            name='party',
            field=models.CharField(blank=True, choices=[('adviser', 'Adviser'), ('intake', 'Intake (retired)'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], max_length=20, null=True),
        ),
    ]
