# Generated by Django 5.1.15 on 2026-05-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_recordauthpin_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordauthpin',
            name='expires_at',
        ),
    ]
