# Generated by Django 5.1.15 on 2026-05-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_ierc_clearances_pin_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordauthpin',
            name='pin',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='recordclearance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
