# Generated by Django 5.1.15 on 2026-09-15 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_pipeline_status_in_review'),
        ('reviews', '0006_alter_recordauthpin_pin_alter_recordclearance_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordclearance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('declined', 'Declined'), ('rejected', 'Rejected'), ('not_cleared', 'Not cleared')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='stage',
            field=models.CharField(choices=[('adviser', 'Adviser'), ('rdco_intake', 'RDCO Intake'), ('intake', 'Intake & Triage'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('declined', 'Resubmission requested'), ('rejected', 'Rejected'), ('negative_finding', 'Negative finding')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='RecordAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(choices=[('adviser', 'Adviser'), ('intake', 'Intake & Triage'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], max_length=20)),
                ('state', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], db_index=True, default='active', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_opened', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='records.record')),
            ],
            options={
                'ordering': ['record', 'opened_at'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.recordassignment'),
        ),
        migrations.CreateModel(
            name='ResubmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(choices=[('adviser', 'Adviser'), ('intake', 'Intake & Triage'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('resubmitted', 'Resubmitted'), ('withdrawn', 'Withdrawn')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmission_requests', to='reviews.recordassignment')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resubmission_requests', to='records.record')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmission_requests_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmission_requests_resolved', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resubmission_requests', to='reviews.review')),
            ],
            options={
                'ordering': ['record', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_party', models.CharField(blank=True, choices=[('adviser', 'Adviser'), ('intake', 'Intake & Triage'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], max_length=20, null=True)),
                ('to_party', models.CharField(choices=[('adviser', 'Adviser'), ('intake', 'Intake & Triage'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('group_id', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_events', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_events', to='records.record')),
            ],
            options={
                'ordering': ['record', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='recordassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('record', 'party'), name='one_active_assignment_per_record_party'),
        ),
        migrations.AddIndex(
            model_name='resubmissionrequest',
            index=models.Index(fields=['record', 'state'], name='reviews_res_record__0f97fc_idx'),
        ),
        migrations.AddIndex(
            model_name='routingevent',
            index=models.Index(fields=['record', 'created_at'], name='reviews_rou_record__94b79b_idx'),
        ),
    ]
