# Generated by Django 5.1.15 on 2026-10-07 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_backfill_shadow_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('assigned', 'Assigned'), ('in_review', 'In review'), ('done', 'Done'), ('withdrawn', 'Withdrawn')], default='assigned', max_length=20)),
                ('source', models.CharField(choices=[('entry', 'Entry'), ('claimed', 'Claimed'), ('assigned', 'Assigned'), ('nominated', 'Nominated'), ('added', 'Added')], max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_seats_assigned', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='reviews.recordassignment')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_seats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assignment', 'assigned_at', 'pk'],
                'indexes': [models.Index(fields=['reviewer', 'state'], name='reviews_rev_reviewe_b57cb6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'withdrawn'), _negated=True), fields=('assignment', 'reviewer'), name='one_live_seat_per_assignment_reviewer')],
            },
        ),
    ]
