# Generated by Django 5.1.15 on 2026-10-08 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_record_version'),
        ('reviews', '0010_backfill_reviewer_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reviews', to='records.recordversion'),
        ),
    ]
