# Generated by Django 5.1.15 on 2026-10-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_review_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordassignment',
            name='closed_by_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='closed_assignments', to='reviews.review'),
        ),
    ]
