# Generated by Django 5.1.15 on 2026-10-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_retire_intake_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordassignment',
            name='party',
            field=models.CharField(choices=[('adviser', 'Adviser'), ('intake', 'Intake (retired)'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resubmissionrequest',
            name='party',
            field=models.CharField(choices=[('adviser', 'Adviser'), ('intake', 'Intake (retired)'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='stage',
            field=models.CharField(choices=[('adviser', 'Adviser'), ('rdco_intake', 'Intake (retired)'), ('intake', 'Intake (retired)'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='routingevent',
            name='from_party',
            field=models.CharField(blank=True, choices=[('adviser', 'Adviser'), ('intake', 'Intake (retired)'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='routingevent',
            name='to_party',
            field=models.CharField(choices=[('adviser', 'Adviser'), ('intake', 'Intake (retired)'), ('itso', 'ITSO'), ('ierc', 'IERC'), ('ktto', 'KTTO'), ('rdco', 'RDCO Final')], max_length=20),
        ),
    ]
