# Generated by Django 5.1.15 on 2026-09-04 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_type', models.CharField(choices=[('internal_call', 'Internal Call'), ('conference_deadline', 'Conference Deadline'), ('funding_window', 'Funding Window'), ('institutional_grant', 'Institutional Grant')], max_length=32)),
                ('title', models.CharField(max_length=300)),
                ('posting_office', models.CharField(max_length=200)),
                ('audience', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('funding_ceiling', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('due_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'opportunities',
                'ordering': ['-is_featured', 'due_date'],
                'indexes': [models.Index(fields=['due_date'], name='opportuniti_due_dat_7609d0_idx')],
            },
        ),
    ]
