"""The cached AI Overview of one record (IR-334).

Replaces a field-less `DocumentSummary` placeholder from migration 0001 that
no code path ever wrote to — the same move IR-89 F made for `DocumentChunk`,
and safe for the same reason.

The overview was regenerated on every page view: `PaperAiOverview` fired
`/ai/ask/` from a `useEffect`, so every visit to a record was a paid vendor
call for an answer that cannot have changed.
"""

from django.db import models


class RecordOverview(models.Model):
    """One record's generated overview, and what it was generated against.

    ``content_hash`` is the active ``ChunkSet``'s hash at generation time, and
    it is the whole invalidation rule: re-chunking a record changes it, which
    makes this row stale and forces one regeneration. ``prompt_version`` does
    the same for a change on our side — editing the overview prompt without
    bumping it would leave every existing row answering the old question.

    **Only the generative state is ever stored.** A row here is an answer; an
    unavailable model is a condition that will pass, and caching it would keep
    a record blank long after the vendor came back.

    ``citations`` holds the wire shape rather than pointers, unlike a stored
    ``Turn`` (ADR-019). The reason the pointer rule exists does not apply: an
    overview is scoped to its own record, so every quote comes from the record
    the reader already opened, and a re-chunk that could stale a quote changes
    ``content_hash`` and discards the row first.
    """

    record = models.OneToOneField(
        "records.Record", on_delete=models.CASCADE, related_name="ai_overview"
    )
    text = models.TextField()
    citations = models.JSONField(default=list, blank=True)
    degraded = models.BooleanField(default=False)
    #: Which model wrote it, so a corpus generated by two models is legible
    #: after the fact rather than silently mixed (the ADR-023 concern).
    model_id = models.CharField(max_length=200, blank=True)
    content_hash = models.CharField(max_length=64)
    prompt_version = models.PositiveSmallIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"RecordOverview(record={self.record_id})"
